# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Past Work
email: alex.balashov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is some of my past work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alexkb0009.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github: [metadata]
github_username:  alexkb0009
social_link: github
social_username: alexkb0009



defaults:
  - scope:
      path: "/_portfolio/"
    values:
      in_portfolio: true

# Build settings
markdown: kramdown
highlighter: true
#theme: minima
theme: jekyll-swiss
theme_color: black
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

image:
  source: ./
  output: generated
  presets:
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 350
    portfolio_thumbnail:
      height: 200

jekyll-archives:
  enabled: ['tags', 'year']
  layout: 'tagpage'
  permalinks:
    year: '/:year/'
    tag: '/tag/:name/'